name: OpenSSF

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call:
    uses: opiproject/actions/.github/workflows/scorecard.yml@main
    secrets: inherit
